# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonas' Blog
description: Hi, my name is Jonas. I created this blog I, as a software enthusiaist, wanted to share some toughts and ideas.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://jonassss.github.io" # the base hostname & protocol for your site
github_username: jonassss
linkedin_username: JHØ

# Build settings
markdown: kramdown
